name: RAG Inference CI Pipeline (Limited to format checks due to lack of GPU)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Basic Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Static Formatting Check
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "src tests"
      - name: Lint check
        uses: astral-sh/ruff-action@v4.0.0
        with:
          src: "src tests"
